In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt
# from skimage import io, transform
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader

from glob import glob

In [ ]:
img_path = glob('./data/images_training_rev1/')

In [2]:
LABEL_HEAD = np.loadtxt('./data/training_solutions_rev1.csv', dtype='str', delimiter=',', )[0]

print(LABEL_HEAD[1:])

['Class1.1' 'Class1.2' 'Class1.3' 'Class2.1' 'Class2.2' 'Class3.1'
 'Class3.2' 'Class4.1' 'Class4.2' 'Class5.1' 'Class5.2' 'Class5.3'
 'Class5.4' 'Class6.1' 'Class6.2' 'Class7.1' 'Class7.2' 'Class7.3'
 'Class8.1' 'Class8.2' 'Class8.3' 'Class8.4' 'Class8.5' 'Class8.6'
 'Class8.7' 'Class9.1' 'Class9.2' 'Class9.3' 'Class10.1' 'Class10.2'
 'Class10.3' 'Class11.1' 'Class11.2' 'Class11.3' 'Class11.4' 'Class11.5'
 'Class11.6']


In [3]:
img_num = np.loadtxt('./data/training_solutions_rev1.csv', dtype='str', delimiter=',', skiprows=1, usecols=(0))


In [10]:
print(img_num)
print(img_num[1]+'.jpg')

['100008' '100023' '100053' ... '999958' '999964' '999967']
100023.jpg


In [5]:
img_class = np.loadtxt('./data/training_solutions_rev1.csv', dtype='float', delimiter=',', skiprows=1, ).T[1:].T

In [6]:
print(img_class)

[[0.383147   0.616853   0.         ... 0.         0.         0.32551225]
 [0.327001   0.663777   0.009222   ... 0.         0.         0.        ]
 [0.765717   0.177352   0.056931   ... 0.         0.         0.        ]
 ...
 [0.202841   0.777376   0.019783   ... 0.         0.         0.07229626]
 [0.091      0.909      0.         ... 0.02306456 0.         0.04533378]
 [0.767      0.14       0.093      ... 0.         0.         0.02338   ]]


In [ ]:
class Galaxydataset(Dataset):
    
    def __init__(self, transform=None):
        self.class_label = LABEL_HEAD[1:]
        self.img_num = img_num
        self.img_class = img_class
        self.img_path = img_path
        
    def __len__(self):
        return len(img_num)
    
    def __getitem__(self, idx):
        
        if torch.is_tensor(idx):
            idx = idx.tolist()
        
        _img = Image.open()
        
        
        
        