In [1]:
import torch
import numpy as np

In [9]:
# A = torch.cuda.is_available()
# print(A)

if torch.cuda.is_available():
    device = torch.device("cuda")

In [2]:
# this is tensor, different from array (still very simmilar)
x = torch.rand(2, 2, dtype=torch.float32)

In [3]:
print(x)
print(x.dtype)
print(x.size())

tensor([[0.0681, 0.6352],
        [0.6979, 0.9649]])
torch.float32
torch.Size([2, 2])


In [4]:
y = torch.tensor([1, 2])
print(y)

tensor([1, 2])


In [8]:
# array to tensor
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [11]:
# tensor operation on gpu

x = torch.ones(5, device=device)
y = torch.ones(5)

y = y.to(device)

z = x + y

print(z)

z = z.to("cpu")

print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
